In [1]:
import pandas as pd

df=pd.read_csv('../data/processed/recipes.csv')

In [19]:
print("All recipes under 30 minutes total time with avg_rating above 4.5: \n")
df.loc[(df['minutes'] < 30) & (df['avg_rating'] > 4.5), ['name','minutes','avg_rating']]

All recipes under 30 minutes total time with avg_rating above 4.5:

                                              name  minutes  avg_rating
10                         calm your nerves  tonic      5.0    5.000000
13                                  chinese  candy     15.0    4.833333
21                emotional balance  spice mixture     10.0    5.000000
30              healthy for them  yogurt popsicles     10.0    4.833333
36      i stole the idea from mirj  sesame noodles     18.0    4.545455
...                                            ...      ...         ...
219407                                    zwieback     19.0    5.000000
219412           zwiebeln salat  swiss onion salad     10.0    5.000000
219415                                zydeco salad      5.0    5.000000
219416                                zydeco sauce     15.0    5.000000
219419                            zydeco spice mix      5.0    5.000000

[51774 rows x 3 columns]

In [20]:
print("All desserts with more than 10 ingredients that STILL have avg_rating above 4.0: \n")
df.loc[(df['category'] == 'desserts') & (df['n_ingredients'] > 10) & (df['avg_rating'] > 4.0), ['name','category','n_ingredients','avg_rating']]

All desserts with more than 10 ingredients that STILL have avg_rating above 4.0:

,name,category,n_ingredients,avg_rating
44,jiffy extra moist carrot cake,desserts,11,4.571429
112,25 pumpkin pie,desserts,12,4.592593
114,250 chocolate chip cookies recipe,desserts,12,5.000000
115,250 00 chocolate chip cookies,desserts,13,5.000000
175,flaky oatmeal raisin cookies,desserts,13,4.750000
...,...,...,...,...
219359,zuke muffins,desserts,11,5.000000
219364,zuni caf scones my version,desserts,11,5.000000
219380,zuppa inglese della nonna,desserts,11,5.000000
219404,zwetschgenkuchen bavarian plum cake,desserts,11,5.000000
219405,zwetschgenkuchen plum cake,desserts,13,5.000000

In [ ]:
print("All recipes below their category's median avg_rating: \n")

avg_rate_per_cat=df.groupby('category')['avg_rating'].transform('median')

df.loc[df['avg_rating'] < avg_rate_per_cat, ['name','category','avg_rating']]

All desserts with more than 10 ingredients that STILL have avg_rating above 4.0:

                                                name     category  avg_rating
1                   a bit different  breakfast pizza    main-dish    4.666667
2                          all in the kitchen  chili    main-dish    4.000000
3                                 alouette  potatoes  side-dishes    4.500000
5                              aww  marinated olives   appetizers    2.000000
7                            beat this  banana bread    breakfast    4.400000
...                                              ...          ...         ...
219410                    zwiebelfleisch  onion beef    main-dish    4.000000
219411   zwiebelkuchen   southwest german onion cake    main-dish    4.166667
219417                            zydeco shrimp wrap    main-dish    3.000000
219421        cookies by design   cookies on a stick     desserts    1.000000
219422  cookies by design   sugar shortbread cookies     desserts    3.000000

[106951 rows x 3 columns]

In [22]:
print("All recipes that are BOTH quick (under 20 minutes) AND simple (5 or fewer ingredients): \n")
df.loc[(df['minutes'] < 20) & (df['n_ingredients'] <= 5), ['name','minutes','n_ingredients']]

All recipes that are BOTH quick (under 20 minutes) AND simple (5 or fewer ingredients):

                                                  name  minutes  n_ingredients
8                          berry  good sandwich spread      5.0              3
10                             calm your nerves  tonic      5.0              5
13                                      chinese  candy     15.0              3
28                                grilled  ranch bread     13.0              3
30                  healthy for them  yogurt popsicles     10.0              3
...                                                ...      ...            ...
219253                       zucchini with serrano ham     15.0              5
219368  zuppa alla pavese  chicken soup w  poached egg     13.0              5
219400                                  zuring  sorrel     15.0              4
219412               zwiebeln salat  swiss onion salad     10.0              5
219415                                    zydeco salad      5.0              4

[18334 rows x 3 columns]