In [39]:
import pandas as pd

df=pd.read_csv('../data/processed/recipes.csv')

In [40]:
ingredient_bucket=pd.cut(df['n_ingredients'], bins=[0,5,10,20,30], labels=['1-5','6-10','11-20','21-30'])
df.pivot_table(index='category',columns=ingredient_bucket,values='avg_rating',aggfunc='mean')

n_ingredients       1-5      6-10     11-20     21-30
category
appetizers     4.639041  4.626113  4.620663  4.723498
beverages      4.692848  4.702725  4.679498  4.166667
breakfast      4.576760  4.565623  4.574397  4.967033
desserts       4.577190  4.546029  4.576769  4.574344
lunch          4.641604  4.628093  4.623034  4.453665
main-dish      4.517809  4.529670  4.559158  4.638615
other          4.617889  4.595929  4.619953  4.672943
side-dishes    4.596066  4.606737  4.620865  4.672053
snacks         4.532044  4.552778  4.708984  4.500000

In [42]:
time_bucket=pd.cut(df['minutes'], bins=[0,5,15,30,60], labels=['1-5 min','6-15 min','16-30 min','31-60 min']).dropna()
time_pivote=df.pivot_table(index='category',columns=time_bucket,aggfunc='size').reset_index()
time_pivote.melt(id_vars='category', var_name='minutes', value_name='size')

       category    minutes   size
0    appetizers    1-5 min   1183
1     beverages    1-5 min   5290
2     breakfast    1-5 min    928
3      desserts    1-5 min   1330
4         lunch    1-5 min    822
5     main-dish    1-5 min    277
6         other    1-5 min   3115
7   side-dishes    1-5 min    245
8        snacks    1-5 min     36
9    appetizers   6-15 min   3791
10    beverages   6-15 min   2679
11    breakfast   6-15 min   2221
12     desserts   6-15 min   4434
13        lunch   6-15 min   2218
14    main-dish   6-15 min   3180
15        other   6-15 min   6887
16  side-dishes   6-15 min   2566
17       snacks   6-15 min     77
18   appetizers  16-30 min   4753
19    beverages  16-30 min    725
20    breakfast  16-30 min   3145
21     desserts  16-30 min   8581
22        lunch  16-30 min   2353
23    main-dish  16-30 min  16953
24        other  16-30 min  10399
25  side-dishes  16-30 min   6092
26       snacks  16-30 min    114
27   appetizers  31-60 min   4087
28    beverages  31-60 min    235
29    breakfast  31-60 min   3155
30     desserts  31-60 min  14126
31        lunch  31-60 min   1578
32    main-dish  31-60 min  24460
33        other  31-60 min  12294
34  side-dishes  31-60 min   7188
35       snacks  31-60 min     75